
package mywsdlpackage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CCSCD1", targetNamespace = "http://xmlns.oracle.com/communications/ncc/2009/05/15/pi", wsdlLocation = "file:/Users/mac/IdeaProjects/TestSOAPClient/src/main/java/Balance_Query.wsdl")
public class CCSCD1
    extends Service
{

    private final static URL CCSCD1_WSDL_LOCATION;
    private final static WebServiceException CCSCD1_EXCEPTION;
    private final static QName CCSCD1_QNAME = new QName("http://xmlns.oracle.com/communications/ncc/2009/05/15/pi", "CCSCD1");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/mac/IdeaProjects/TestSOAPClient/src/main/java/Balance_Query.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CCSCD1_WSDL_LOCATION = url;
        CCSCD1_EXCEPTION = e;
    }

    public CCSCD1() {
        super(__getWsdlLocation(), CCSCD1_QNAME);
    }

    public CCSCD1(WebServiceFeature... features) {
        super(__getWsdlLocation(), CCSCD1_QNAME, features);
    }

    public CCSCD1(URL wsdlLocation) {
        super(wsdlLocation, CCSCD1_QNAME);
    }

    public CCSCD1(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CCSCD1_QNAME, features);
    }

    public CCSCD1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CCSCD1(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CCSCD1PortType
     */
    @WebEndpoint(name = "CCSCD1HttpSoap11Endpoint")
    public CCSCD1PortType getCCSCD1HttpSoap11Endpoint() {
        return super.getPort(new QName("http://xmlns.oracle.com/communications/ncc/2009/05/15/pi", "CCSCD1HttpSoap11Endpoint"), CCSCD1PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CCSCD1PortType
     */
    @WebEndpoint(name = "CCSCD1HttpSoap11Endpoint")
    public CCSCD1PortType getCCSCD1HttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/communications/ncc/2009/05/15/pi", "CCSCD1HttpSoap11Endpoint"), CCSCD1PortType.class, features);
    }

    /**
     * 
     * @return
     *     returns CCSCD1PortType
     */
    @WebEndpoint(name = "CCSCD1HttpSoap12Endpoint")
    public CCSCD1PortType getCCSCD1HttpSoap12Endpoint() {
        return super.getPort(new QName("http://xmlns.oracle.com/communications/ncc/2009/05/15/pi", "CCSCD1HttpSoap12Endpoint"), CCSCD1PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CCSCD1PortType
     */
    @WebEndpoint(name = "CCSCD1HttpSoap12Endpoint")
    public CCSCD1PortType getCCSCD1HttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/communications/ncc/2009/05/15/pi", "CCSCD1HttpSoap12Endpoint"), CCSCD1PortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CCSCD1_EXCEPTION!= null) {
            throw CCSCD1_EXCEPTION;
        }
        return CCSCD1_WSDL_LOCATION;
    }

}
