
package mywsdlpackage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CCSCD1PortType", targetNamespace = "http://xmlns.oracle.com/communications/ncc/2009/05/15/pi")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CCSCD1PortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns mywsdlpackage.CCSCD1ADDResponse
     * @throws CCSCD1ADDFault_Exception
     */
    @WebMethod(operationName = "CCSCD1_ADD", action = "urn:CCSCD1_ADD")
    @WebResult(name = "CCSCD1_ADDResponse", targetNamespace = "http://xmlns.oracle.com/communications/ncc/2009/05/15/pi", partName = "parameters")
    public CCSCD1ADDResponse ccscd1ADD(
        @WebParam(name = "CCSCD1_ADD", targetNamespace = "http://xmlns.oracle.com/communications/ncc/2009/05/15/pi", partName = "parameters")
        CCSCD1ADD parameters)
        throws CCSCD1ADDFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns mywsdlpackage.CCSCD1CHGResponse
     * @throws CCSCD1CHGFault_Exception
     */
    @WebMethod(operationName = "CCSCD1_CHG", action = "urn:CCSCD1_CHG")
    @WebResult(name = "CCSCD1_CHGResponse", targetNamespace = "http://xmlns.oracle.com/communications/ncc/2009/05/15/pi", partName = "parameters")
    public CCSCD1CHGResponse ccscd1CHG(
        @WebParam(name = "CCSCD1_CHG", targetNamespace = "http://xmlns.oracle.com/communications/ncc/2009/05/15/pi", partName = "parameters")
        CCSCD1CHG parameters)
        throws CCSCD1CHGFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns mywsdlpackage.CCSCD1DELResponse
     * @throws CCSCD1DELFault_Exception
     */
    @WebMethod(operationName = "CCSCD1_DEL", action = "urn:CCSCD1_DEL")
    @WebResult(name = "CCSCD1_DELResponse", targetNamespace = "http://xmlns.oracle.com/communications/ncc/2009/05/15/pi", partName = "parameters")
    public CCSCD1DELResponse ccscd1DEL(
        @WebParam(name = "CCSCD1_DEL", targetNamespace = "http://xmlns.oracle.com/communications/ncc/2009/05/15/pi", partName = "parameters")
        CCSCD1DEL parameters)
        throws CCSCD1DELFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns mywsdlpackage.CCSCD1QRYResponse
     * @throws CCSCD1QRYFault_Exception
     */
    @WebMethod(operationName = "CCSCD1_QRY", action = "urn:CCSCD1_QRY")
    @WebResult(name = "CCSCD1_QRYResponse", targetNamespace = "http://xmlns.oracle.com/communications/ncc/2009/05/15/pi", partName = "parameters")
    public CCSCD1QRYResponse ccscd1QRY(
        @WebParam(name = "CCSCD1_QRY", targetNamespace = "http://xmlns.oracle.com/communications/ncc/2009/05/15/pi", partName = "parameters")
        CCSCD1QRY parameters)
        throws CCSCD1QRYFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns mywsdlpackage.CCSCD1MSWResponse
     * @throws CCSCD1MSWFault_Exception
     */
    @WebMethod(operationName = "CCSCD1_MSW", action = "urn:CCSCD1_MSW")
    @WebResult(name = "CCSCD1_MSWResponse", targetNamespace = "http://xmlns.oracle.com/communications/ncc/2009/05/15/pi", partName = "parameters")
    public CCSCD1MSWResponse ccscd1MSW(
        @WebParam(name = "CCSCD1_MSW", targetNamespace = "http://xmlns.oracle.com/communications/ncc/2009/05/15/pi", partName = "parameters")
        CCSCD1MSW parameters)
        throws CCSCD1MSWFault_Exception
    ;

}
